server:
  port: 8888

logging:
  path: logs
  file: mylog.log


spring:
  application:
    name: report
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/course
    username: root
    password: toor

mybatis:
  type-aliases-package: com.course.com.course.model
  mapper-locations:
    - mapper/*
